---
title: "Grid Frequency Analysis"
author: "Michael Bülow Pedersen"
output: pdf_document
---

## Research Objects

1. Download data from API and Web.
2. Store and handle a large dataset of $`r format(365*24*60*60+1,scientific=FALSE,big.mark = ",")`$ observations per year.
3. Create beautiful, informative graphs.
4. Produce reproducable research.
5. Make a shiny/rStudio presentation showing results.
6. Answer research questions:
    + is the frequency exactly 50 Hz on average?
    + what differences in frequency quality can be observed between the Nordic and Continental electricity grids?
    

## Introduction

The European electricity grid consists of several distinct frequency areas. One frequency area is the Nordic grid which covers Norway, Finland, Sweden and Eastern Denmark. Another frequency area is the Continental grid which covers countries such as Germany, France, Spain, Portugal, Italy, Slovenia, Czech Republic, Switzerland, Slovkia, Poland, and all the way to the border of Turkey...

To keep a power grid stable, it is necessary for the grid frequency to move within a narrow band around a predetermind value. 
For European countries the grid frequency has been set at reference frequency of 50 Hz+-1mHz. Whenever the frequency moves below this level, Transmission System Operators have contracted grid connected market participants to supply power to the grid at seconds notice. Similarly, if the frequency moves above 50 Hz TSO's have contracted participants to withdraw power from the grid. In the Continental grid extreme events are characterized by frequencies +- 100 mHz. Especially the low frequencies are critical because below -100 mHz all primary reserves have been exhausted and the grid cannot cope with additional loss off generation. Below -150 mHz there is a risk of power plants dropping out. On the other hand, at +200 mHz solar panels begin to risk dropping out..

Interestingly, it has also been agreed to run the power system at exactly 50 Hz on average. Because accumulated short-term frequency deviations can move the average above 50 Hz on one day, it is necessary to correct the grid frequency by setting a lower frequency point on subsequent days. We should therefore be able to observe autoregressive effects in the daily average frequency measurements.
Because of this correction, it should be possible to set a watch by measuring the grid frequency (give or take about a minute). 
We will test whether the information in this paragraph is indeed correct.

## Getting the data

### Nordic

We can query the API of the [Norwegian TSO Statnett](http://www.statnett.no/en/Market-and-operations/) to get 1 second measurements. This gives $`r format(365*24*60*60,scientific=FALSE,big.mark = ",")`$ observations per year.

### Continental

We can query the Website of the [French TSO RTE](http://clients.rte-france.com/lang/an/clients_producteurs/vie/vie_frequence.jsp) to get 10 second measuremetns. This gives $`r format(365*24*60*60/10,scientific=FALSE,big.mark = ",")`$ observations per year.

